language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
before_install:
  - cd react-ui/
install:
  - npm install
  - npm install --only=dev --no-shrinkwrap
script:
  - cd react-ui && npm test